### ISSUE TITLE
Compatiblity, extendability, discoverability, and documentation

### ISSUE THREAD

**Issue by Rodentman87** [Bit-Studios/KerbalWebProgram#17]
Right now, there's very few available methods in the API, however, as this mod expands and once we add the ability for other mods to add their own methods, it will be important to have the API be as consistent and discoverable as possible. I think there's a few steps we can take to start going down that road right now before we do any work on an API for other mods.

## 1. A method to list out all the available methods on the API

This will allow API consumers to quickly get a list of all the available methods in the API in case our documentation happens to drift and be missing some.

## 2. Parameter validation

When registering methods, we should also register the parameters and their types. That way we can do some validation before it even reaches the handler for that method, cleaning up the amount of code needed in a handler while also reducing bugs. This will also let us make a consistent format for validation errors being returned to clients.

## 3. Auto-generated documentation

By combining the two above, as well as having modders pass some other documentation related info (short description, tags, etc.) when registering a method, we can return all that info in the method that lists all available methods and create a small page that will automatically generate documentation from that endpoint. This means that the documentation will always be up to date with whichever version of the mod the user is using, as well as any 3rd party mods providing methods.

The exact ways in which each of these things will work in the end will still need to be discussed, but I think these 3 points are very important to making this mod as useful and usable as possible.

**Comment by NathanPeake** [comment]
![image](https://user-images.githubusercontent.com/37817019/221740305-c110ebdc-38a1-4827-b953-143be6334f09.png)
what do you think of this?

**Comment by NathanPeake** [comment]
Basic parameter checking using that system
![image](https://user-images.githubusercontent.com/37817019/221741638-a3e326c8-1ad9-4e74-931f-5b45bad5aa32.png)

**Comment by Rodentman87** [comment]
That looks pretty ok, I was more thinking along the lines of something where we have a class for each parameter type (StringParameter, NumberParameter, etc.) and then when validating the parameters, we can have the code for validation contained within those classes, and it would allow us to add additional types of validation for things, like max or min string length, only accepting a certain set of values, etc. This would also allow us to have optional parameters. So the process would look something like:
```
1. Method is registered with its parameters as a list of class instances
2. Request comes in for that method
3. Iterate over the list of parameters and pass each value from the request to the validation function
4. If the validation function throws an error, save that message under the key for that option
5. If there's no validation errors, run the method's handler
6. If there is errors, return a response with the key 'errors' containing an object with the errors matched to their parameter names
```

**Comment by NathanPeake** [comment]
![image](https://user-images.githubusercontent.com/37817019/221747967-2ccf05c6-adf7-4201-a172-20f8f3d9dc74.png)

**Comment by NathanPeake** [comment]
![image](https://user-images.githubusercontent.com/37817019/221748021-676e8b2b-6a54-4980-a228-e827843d994b.png)

**Comment by NathanPeake** [comment]
Min max checker 

![Image](https://user-images.githubusercontent.com/37817019/221750724-f2554f42-fda3-4d97-947e-b797c3d11b01.png)
