### ISSUE TITLE
setShipThrottle name is misleading

### ISSUE THREAD

**Issue by Rodentman87** [Bit-Studios/KerbalWebProgram#32]
The method for `setShipThrottle` is a little misleading in that it doesn't actually set the throttle and instead applies a delta to the throttle constantly until changed. I think the method should either be renamed or change the method to actually setting the throttle instead of applying a throttle.

**Comment by NathanPeake** [comment]
A new way was figured out yesterday https://discord.com/channels/1078696971088433153/1078841771771056280/1082056297735802940

**Comment by NathanPeake** [comment]
Tested this way with one of my other mods https://github.com/Bit-Studios/SuicideBurn and it works. will change it to this.

**Comment by NathanPeake** [comment]
This is now fixed with this https://github.com/Bit-Studios/KerbalWebProgram/blob/13cf88b6bc922e66355e57102f117c457bf0a8ed/ApiEndpointsBuiltIn.cs#L301
